# Generated by Django 6.1 on 2026-08-09 09:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MaxLengthValidator(200)],
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[django.core.validators.MaxLengthValidator(200)],
                    ),
                ),
                (
                    "active_substance",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[django.core.validators.MaxLengthValidator(200)],
                    ),
                ),
                (
                    "form",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("liquid", "Liquid"),
                            ("injection", "Injection"),
                            ("ointment", "Ointment"),
                            ("powder", "Powder"),
                            ("drops", "Drops"),
                            ("spray", "Spray"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=255,
                        validators=[django.core.validators.MaxLengthValidator(20)],
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[django.core.validators.MaxLengthValidator(100)],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MaxLengthValidator(50)],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "withdrawal_period_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "minimum_stock_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("requires_prescription", models.BooleanField(default=False)),
                ("is_controlled_substance", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MedicineBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MaxLengthValidator(100)],
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[django.core.validators.MaxLengthValidator(200)],
                    ),
                ),
                ("expiry_date", models.DateField()),
                ("received_at", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="clinical_data.medicine",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date"],
                "unique_together": {("medicine", "batch_number")},
            },
        ),
    ]
