# Generated by Django 6.1 on 2026-08-09 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical_data", "0002_visit_prescribedmedicine_visitnote"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visitnote",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="visitnote",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="clinical_data.visit",
            ),
        ),
    ]
