# Generated by Django 6.0.8 on 2026-08-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_data', '0002_visit_prescribedmedicine_visitnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinebatch',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
