# Generated by Django 6.0.8 on 2026-08-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_data', '0004_service_visitservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='visitservice',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
