# Generated by Django 6.0.8 on 2026-08-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical_data", "0005_service_tax_rate_visitservice_tax_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitservice",
            name="notification_channel",
            field=models.CharField(
                blank=True,
                choices=[("email", "Email"), ("sms", "SMS")],
                help_text="How to remind the client before this expires. Falls back to the client's preferred channel when blank.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="visitservice",
            name="vaccine_valid_until",
            field=models.DateField(
                blank=True,
                help_text="Date the vaccine's protection ends and a booster is due.",
                null=True,
            ),
        ),
    ]
