# Generated by Django 6.1 on 2026-08-08 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_date_joined_alter_user_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[django.core.validators.MaxLengthValidator(100)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(20)],
                verbose_name="phone number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="specializations",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="user.specialization",
                verbose_name="specializations",
            ),
        ),
    ]
