# Generated by Django 6.0.8 on 2026-08-12 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="city",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="first_name",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(150)],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(150)],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(20)],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="postal_code",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(20)],
            ),
        ),
    ]
