# Generated by Django 6.0.8 on 2026-08-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_client_city_alter_client_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="preferred_notification_channel",
            field=models.CharField(
                choices=[("email", "Email"), ("sms", "SMS")],
                default="email",
                max_length=10,
            ),
        ),
    ]
