# Generated by Django 6.0.8 on 2026-08-12 22:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
        ("clients", "0002_alter_client_city_alter_client_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(150)],
            ),
        ),
        migrations.AlterField(
            model_name="animaltype",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[django.core.validators.MaxLengthValidator(100)],
            ),
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MaxLengthValidator(150)],
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=255,
                        validators=[django.core.validators.MaxLengthValidator(10)],
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[django.core.validators.MaxLengthValidator(100)],
                    ),
                ),
                (
                    "microchip_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        validators=[django.core.validators.MaxLengthValidator(50)],
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("is_sterilized", models.BooleanField(default=False)),
                ("is_deceased", models.BooleanField(default=False)),
                ("date_of_death", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patients",
                        to="animals.animal",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patients",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PatientWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=5)),
                ("recorded_at", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weight_records",
                        to="animals.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
    ]
