# Generated by Django 6.1 on 2026-08-07 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_patient_patientweight"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="animal",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(150)],
            ),
        ),
        migrations.AlterField(
            model_name="animaltype",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[django.core.validators.MaxLengthValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="color",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="microchip_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                validators=[django.core.validators.MaxLengthValidator(50)],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(150)],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="sex",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=255,
                validators=[django.core.validators.MaxLengthValidator(10)],
            ),
        ),
    ]
