from django.urls import path

from clinical_data import views

urlpatterns = [
    path(
        "medicines/",
        views.MedicineListCreateView.as_view(),
        name="medicine_list_create",
    ),
    path(
        "medicines/<int:pk>/",
        views.MedicineDetailView.as_view(),
        name="medicine_detail",
    ),
    path(
        "medicines/batches/",
        views.MedicineBatchListCreateView.as_view(),
        name="medicine_batch_list_create",
    ),
    path(
        "medicines/batches/<int:pk>/",
        views.MedicineBatchDetailView.as_view(),
        name="medicine_batch_detail",
    ),
    path(
        "visits/",
        views.VisitListCreateView.as_view(),
        name="visit_list_create",
    ),
    path(
        "visits/<int:pk>/",
        views.VisitDetailView.as_view(),
        name="visit_detail",
    ),
    path(
        "visits/<int:pk>/full/",
        views.VisitDetailWithDetailsView.as_view(),
        name="visit_detail_full",
    ),
    path(
        "visits/notes/",
        views.VisitNoteListCreateView.as_view(),
        name="visit_note_list_create",
    ),
    path(
        "visits/notes/<int:pk>/",
        views.VisitNoteDetailView.as_view(),
        name="visit_note_detail",
    ),
    path(
        "visits/medicines/",
        views.PrescribedMedicineListCreateView.as_view(),
        name="prescribed_medicine_list_create",
    ),
    path(
        "visits/medicines/<int:pk>/",
        views.PrescribedMedicineDetailView.as_view(),
        name="prescribed_medicine_detail",
    ),
    path(
        "services/",
        views.ServiceListCreateView.as_view(),
        name="service_list_create",
    ),
    path(
        "services/<int:pk>/",
        views.ServiceDetailView.as_view(),
        name="service_detail",
    ),
    path(
        "visits/services/",
        views.VisitServiceListCreateView.as_view(),
        name="visit_service_list_create",
    ),
    path(
        "visits/services/<int:pk>/",
        views.VisitServiceDetailView.as_view(),
        name="visit_service_detail",
    ),
]
